// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhmohjnjwrivhglnzuqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhobW9oam5qd3JpdmhnbG56dXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTk0NzcsImV4cCI6MjA2MzgzNTQ3N30.Zuk65hee4wPZXIaMzRRJrQd_jOhVnqtZQmu978XRuP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);